---

- name: make sure hostname is in hosts file
  replace:
    dest: /etc/hosts
    regexp: '^(127\.0\.0\.1(?!.*\b{{ inventory_hostname }}\b).*)$'
    replace: '127.0.0.1 localhost {{ inventory_hostname }}'

- name: change sh directory from dash to bash
  shell: >-
    rm /bin/sh &&
    ln -s /bin/bash /bin/sh
  when:
    - ansible_distribution in ["Ubuntu","Debian"]

- name: install epel-release when online env
  yum:
    name: epel-release
    state: present
  when:
    - ansible_distribution in ["CentOS","RedHat"]
    - not pkg_repo_url != ""

- name: install python-pip
  yum:
    name: python-pip
    state: present
  when:
    - ansible_distribution in ["CentOS","RedHat"]

- name: install jq packages
  package:
    name: "{{ item }}"
    state: present
  loop:
    - jq

- import_tasks: setup-interfaces.yml
- import_tasks: setup-net-services.yml
