---
- name: include global default variables
  import_playbook: ../include_defaults.yml

- hosts: localhost
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
  roles:
    - { role: ../kubespray/roles/kubespray-defaults }
    - { role: ../kubespray/roles/container-engine }
    - { role: container-registry/client }
  tags: always

- import_playbook: ../kubespray/cluster.yml
  when: not exclude_k8s_images

- hosts: localhost
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
  roles:
    - { role: taco-apps/istio/prepare }
  tags: always

- hosts: localhost
  name: download k8s clients
  roles:
    - { role: k8s/clients }
  vars:
    artifacts_dir: "{{ local_release_dir }}"
    install_k8s_clients: false

- hosts: localhost
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
  roles:
    - { role: ../kubespray/roles/kubespray-defaults }
    - { role: prepare-artifact }
  tags: always
