---
- name: copy helm binary to ansible host
  fetch:
    src: "{{ bin_dir }}/helm"
    dest: "{{ artifacts_dir }}/helm"
    flat: yes
    validate_checksum: no
  become: no
  delegate_to: "{{ groups['kube-master']|first }}"

- name: copy helm to bin_dir
  copy:
    src: "{{ artifacts_dir }}/helm"
    dest: "{{ bin_dir }}/helm"
    mode: 0755
