---
- name: copy admin kubeconfig to ansible host
  fetch:
    src: "/root/.kube/config"
    dest: "{{ artifacts_dir }}/{{ cluster_name }}-admin.conf"
    flat: yes
    validate_checksum: no
  delegate_to: "{{ groups['kube-master']|first }}"

- name: create kube config dir
  file:
    path: "{{ lookup('env','HOME') }}/.kube"
    mode: "0700"
    state: directory
  become: no

- name: copy admin kubeconfig to home
  copy:
    src: "{{ artifacts_dir }}/{{ cluster_name }}-admin.conf"
    dest: "{{ lookup('env','HOME') }}/.kube/{{ cluster_name }}-config"
  become: no

- name: copy kubectl binary to ansible host
  fetch:
    src: "{{ bin_dir }}/kubectl"
    dest: "{{ artifacts_dir }}/kubectl"
    flat: yes
    validate_checksum: no
  delegate_to: "{{ groups['kube-master']|first }}"

- name: copy kubectl to bin_dir
  copy:
    src: "{{ artifacts_dir }}/kubectl"
    dest: "{{ bin_dir }}/kubectl"
    mode: 0755

- name: check whether .bashrc contains PATH
  command: grep -Frn "export PATH=" {{ lookup('env','HOME') }}/.bashrc
  register: checkpath
  ignore_errors: True
  changed_when: False

- name: add PATH into bashrc
  lineinfile:
    dest: "{{ lookup('env','HOME') }}/.bashrc"
    state: present
    line: 'export PATH=$PATH:{{bin_dir}}'
  when: not checkpath.rc == 0

- name: add {{ bin_dir }} to PATH
  lineinfile:
    path: "{{ lookup('env','HOME') }}/.bashrc"
    state: present
    regexp: 'export PATH=(["]*)((?!.*?{{bin_dir}}).*?)(["]*)$'
    line: 'export PATH=\1\2:{{bin_dir}}\3'
    backrefs: yes
  become: no
  when: checkpath.rc == 0

- name: check whether .bashrc contains KUBECONFIG
  command: grep -Frn "export KUBECONFIG=" {{ lookup('env','HOME') }}/.bashrc
  register: kubeconfig_grep_result
  ignore_errors: True
  changed_when: False

- name: add KUBECONFIG into bashrc
  lineinfile:
    dest: "{{ lookup('env','HOME') }}/.bashrc"
    state: present
    line: 'export KUBECONFIG=$HOME/.kube/{{ cluster_name }}-config'
  become: no
  when: not kubeconfig_grep_result.rc == 0

- name: add {{ cluster_name }}-config to KUBECONFIG
  lineinfile:
    path: "{{ lookup('env','HOME') }}/.bashrc"
    state: present
    regexp: 'export KUBECONFIG=(.*config)+$'
    line: 'export KUBECONFIG=\1:$HOME/.kube/{{ cluster_name }}-config'
    backrefs: yes
  become: no
  when: kubeconfig_grep_result.rc == 0

- name: source bashrc
  become: no
  shell: source {{ lookup('env','HOME') }}/.bashrc
  args:
    executable: /bin/bash
